### PR TITLE
Static user data fetch script and dump

### PR DESCRIPTION
**Pull request by darshkpatel**
* Added script to fetch and save pod details for fellowship members
* Dump of static user data

### CODE REVIEW

**Comment by sauravhiremath** [comment]
- So are we keeping this as a script only? (Can be run only when there is an update)
- Could you run a sanity check on json with usernames as key ( to ensure there are no repeated values). You have already excluded parent teams, and it should work fine for now. But if in future any other nested teams are added, then sanity check could work) - Can just loop over the list to remove duplicates as the last step
- Also, do we keep this fetched data in memory (as json in repo) or store it in a DB?

**Comment by darshkpatel** [comment]
> * So are we keeping this as a script only? (Can be run only when there is an update)

Yep, Users and their pods will remain static throughout the fellowship, in case the need arises the script can be used to update the users 

> * Also, do we keep this fetched data in memory (as JSON in repo) or store it in a DB?

 small list, can be kept in memory itself, plus we aren't running any complex queries on these either

**Comment by darshkpatel** [comment]
>Could you run a sanity check on json with usernames as key ( to ensure there are no repeated values). You have already excluded parent teams, and it should work fine for now. But if in future any other nested teams are added, then sanity check could work) - Can just loop over the list to remove duplicates as the last step

Was a bigger problem , added support for people with multiple pods!

**Review by sauravhiremath — APPROVED** [review]
Yeah LGTM. Can run the scripts again to update it

**Comment by darshkpatel** [comment]
> Yeah LGTM. Can run the scripts again to update it

Already done in cc33418

**Pull request merged**
