### PR TITLE
[Docs] Readme/Docs updates and changes

### PR DESCRIPTION
**Pull request by sauravhiremath**
- [x] Added react and node CI build status

P.s: This PR will be kept open for a few days, to accumulate all README and docs updates. Any changes for READMEs are welcomed here

### CODE REVIEW

**Comment by sauravhiremath** [comment]
@all-contributors add darshkpatel for code

**Comment by sauravhiremath** [comment]
@all-contributors add kunal-kushwaha for doc and ideas

**Comment by sauravhiremath** [comment]
@all-contributors add sauravhiremath for code, doc and design

**Comment by darshkpatel** [comment]
@all-contributors add @sauravhiremath for code and UI

Edit: !badbot

Edit2: !goodbot

**Comment by sauravhiremath** [comment]
HOW CAN WE STOP GITHUB FROM RUNNING CI EVERYTIME!!!??

**Comment by darshkpatel** [comment]
Set paths
```on:
  push:
      - 'backend/**'
```

**Comment by kunal-kushwaha** [comment]
@all-contributors add kunal-kushwaha for doc and ideas

**Comment by darshkpatel** [comment]
> @kunal-kushwaha
> 
> I've updated [the pull request](https://github.com/bundly/dash/pull/33) to add @kunal! 🎉

!badbot

@all-contributors add @kunal-kushwaha for docs and ideas

**Comment by sauravhiremath** [comment]
> Set paths
> 
> ```
>   push:
>       - 'backend/**'
> ```

Any way to stop vercel for doing so? I don't see any config options on vercel dashboard, maybe possible with vercel yml in the project?

**Pull request merged**
