### PR TITLE
Basic Github Notification Feed 

### LINKED ISSUE #2: Make Github Activity Component
See user's activity from github and generate summary

### PR DESCRIPTION
**Pull request by darshkpatel**
Mark, as Read and Add to ToDo, left to implement 
Resolves: #2

### CODE REVIEW

**Comment by sauravhiremath** [comment]
Eslintify it maybe. Other than that LGTM

**Review by sauravhiremath — CHANGES_REQUESTED** [review]
- Could you rebase/merge with master
- Where is it rendering the notifications? Coz I can see the components added, but not imported anywhere to render. Maybe I missed something
- Eslintify it maybe. Other than that LGTM

**Comment by darshkpatel** [comment]
Lemme add eslint config too

**Comment by darshkpatel** [comment]
> * Could you rebase/merge with master

Done

> * Where is it rendering the notifications? Coz I can see the components added, but not imported anywhere to render. Maybe I missed something

Haven't imported it, since we'd ideally import it in the dashboard

**Review by sauravhiremath — APPROVED** [review]
Changes made. LGTM

**Pull request merged**
